package org.prlprg.ir.type;

import org.prlprg.ir.CFG;
import org.prlprg.rshruntime.TypeFeedback;
import org.prlprg.sexp.*;
import org.prlprg.util.NotImplementedError;

/**
 * All global {@link RType}s and methods to create {@link RType}s are here so they're easy to find.
 */
public class RTypes {
  /** The type of an expression which hangs, errors, or otherwise diverts control flow. */
  public static final RType NOTHING = new RTypeNothing();

  /**
   * The type of a value we know absolutely nothing about (this is common, e.g. arbitrary {@code
   * LdVar}).
   */
  public static final RType ANY = new RTypeAny();

  /** The (most precise representable) type of the given value. */
  public static RType of(SEXP value) {
    return new RTypeImpl(value, RBaseType.of(value), RClosureType.of(value), RTypeFlags.of(value));
  }

  /** The type of a value which passes the assumptions generated by the feedback. */
  public static RType assume(TypeFeedback feedback) {
    throw new NotImplementedError();
  }

  /** The return type of this static call. TODO: Replace param call with {@code Closure} */
  public static RType staticCallReturn(CFG call) {
    throw new NotImplementedError();
  }

  /** The type after forcing this type. */
  public static RType force(RType forced) {
    throw new NotImplementedError();
  }

  /**
   * The type of a value we know has a specific {@link SEXPType} and no weirdness (no object or
   * attributes), produced by builtins e.g. {@code LdFun}. If {@code type} is the type of a
   * primitive vector, this will also return the type for a scalar.
   */
  public static RType simple(SEXPType type) {
    throw new NotImplementedError();
  }

  private RTypes() {}
}
