// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package rsh.server.protocol;

public interface CompileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rsh.server.protocol.CompileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string failure = 2;</code>
   * @return The failure.
   */
  java.lang.String getFailure();
  /**
   * <code>string failure = 2;</code>
   * @return The bytes for failure.
   */
  com.google.protobuf.ByteString
      getFailureBytes();

  /**
   * <code>.rsh.server.protocol.CompileResponse.Result result = 3;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <code>.rsh.server.protocol.CompileResponse.Result result = 3;</code>
   * @return The result.
   */
  rsh.server.protocol.CompileResponse.Result getResult();
  /**
   * <code>.rsh.server.protocol.CompileResponse.Result result = 3;</code>
   */
  rsh.server.protocol.CompileResponse.ResultOrBuilder getResultOrBuilder();

  public rsh.server.protocol.CompileResponse.DataCase getDataCase();
}
