// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package rsh.server.protocol;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rsh.server.protocol.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rsh.server.protocol.CompileRequest compile = 2;</code>
   * @return Whether the compile field is set.
   */
  boolean hasCompile();
  /**
   * <code>.rsh.server.protocol.CompileRequest compile = 2;</code>
   * @return The compile.
   */
  rsh.server.protocol.CompileRequest getCompile();
  /**
   * <code>.rsh.server.protocol.CompileRequest compile = 2;</code>
   */
  rsh.server.protocol.CompileRequestOrBuilder getCompileOrBuilder();

  public rsh.server.protocol.Request.DataCase getDataCase();
}
