---
title: "Benchmarks Analysis"
output: html_document
date: 2025-07-17
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(FactoMineR)
library(factoextra)


here::i_am("rsh/inst/benchmarks/analysis/benchmarks.Rmd")

library(here)

geom_mean <- function(xs) {
  exp(mean(log(na.omit(xs))))
}

DEFAULT_WARMUP <- 5
```

```{r load-data}
# Load the benchmark data
bench_rsh <- read_csv(here("rsh", "benchmark-results", "20250716-193400-e53c63d7", "benchmarks.csv"), col_types = cols(timestamp = col_datetime())) |>
    rename(VM=expr)
bench_bc <- read_csv(here("rsh", "benchmark-results", "baseline", "benchmarks.csv"), col_types = cols(timestamp = col_datetime())) |>
    rename(VM=expr)
bc_profiles <- read_csv(here("rsh", "bcprof-results", "merged_output.csv"), col_types = cols(timestamp = col_datetime()))
```


# Speedups

```{r compute-speedup}
compute_mean <- function(bench) bench |>
  group_by(VM, name) |>
  slice(-(1:DEFAULT_WARMUP)) |># remove warmup
  summarize(
    mean_time = mean(time / 1e6)
  )

speedups <- compute_mean(bench_rsh) |> 
    left_join(compute_mean(bench_bc), by = c("name"), suffix = c("_rsh", "_bc")) |>
    group_by(name) |>
    summarize(
      speedup = mean_time_bc / mean_time_rsh
    ) 

speedups
```

```{r summary-speedup}
speedups |>
    summarize(
        mean = geom_mean(speedup),
        median = median(speedup),
        min = min(speedup),
        max = max(speedup),
        sd = sd(speedup)
    ) 
```

# Bytecode profiler 

```{r bytecode}
df <- select(bc_profiles, -param, -commit, -timestamp) |> 
    left_join(speedups, by = "name") |>
    relocate(speedup, .after = name)
knitr::kable(df, digits = 2, caption = "Bytecode profiler results with speedups") 
```


```{r ranking-opcodes}
calculate_percentages <- function(data) {
  # Select only numeric columns
  numeric_cols <- select(data, -opcode)

  # Calculate total for each numeric column
  totals <- colSums(numeric_cols, na.rm = TRUE)

  # Calculate percentages
  data %>%
    mutate(across(-opcode, ~ .x / totals[cur_column()] * 100, .names = "{.col}_pct"))
}

opcode_hits <- select(df, name, matches("^[A-Z0-9_]+$", ignore.case=FALSE)) |>
  pivot_longer(-name, names_to = "opcode", values_to = "hits") |> 
  pivot_wider(names_from = "name", values_from = "hits", values_fill = 0) 
opcode_pcts <- calculate_percentages(opcode_hits)
opcode_pcts |> select(opcode, ends_with("_pct")) |>
  knitr::kable(digits = 2, caption = "Opcode hits percentages")
```


Get the geometric mean of opcode percentages: 
```{r opcode-geometric-mean}
opcode_hits |> rowwise(opcode) |>
  summarize(hits = sum(across(everything()))) |>
  ungroup() |>
  mutate(pct = hits / sum(hits) * 100) |>
  arrange(desc(hits)) |>
  mutate(cpct = cumsum(pct)) |>
  knitr::kable(digits = 2, caption = "Geometric mean of opcode percentages")
``` 

# PCA 

```{r pca}
pca <- prcomp(select(df, -name), center = TRUE, scale = TRUE)
summary(pca)
```

```{r pca-loadings}
pca$rotation
```

```{r pca-plot}
biplot(pca, scale = 0, cex = 0.5, expand=3, xlim= c(-70, 40), ylim = c(-20, 70)) 
```

Using FactorMineR:

```{r pca-facto}
pca_fm <- PCA(select(df, name, speedup, matches("^[A-Z0-9_]+$", ignore.case=FALSE)), 
  scale.unit=TRUE, ncp=5, quanti.sup=2, quali.sup=1, graph = FALSE)
#plot.PCA(pca_fm, axes=c(1, 2), choix="var", habillage=1, cex=0.7)
# https://stackoverflow.com/questions/59865922/visualizing-pca-with-large-number-of-variables-in-r-using-ggbiplot
fviz_pca_biplot(pca_fm, repel = TRUE, select.var = list(contrib = 5))
```

# Random forests

```{r random-forest}
library(randomForest)
library(caret)
set.seed(42)
```

```{r datasets}
ind <- sample(2, nrow(df), replace = TRUE, prob = c(0.7, 0.3))
features <- select(df, -name)
train <- features[ind == 1, ]
test <- features[ind == 2, ]
```

```{r rf-model}
rf_model <- randomForest(speedup ~ ., data = train, importance = TRUE, ntree = 1000)
rf_model
```

```{r importance}
imp <- as.data.frame(importance(rf_model)) |>
  arrange(desc(`%IncMSE`))
imp
```

```{r importance-plot,  fig.width=12, fig.height=12}
ImpData <- as.data.frame(importance(rf_model))
ImpData$Var.Names <- row.names(ImpData)

ggplot(ImpData, aes(x=Var.Names, y=`%IncMSE`)) +
  geom_segment( aes(x=Var.Names, xend=Var.Names, y=0, yend=`%IncMSE`), color="skyblue") +
  geom_point(aes(size = IncNodePurity), color="blue", alpha=0.6) +
  expand_limits(x= c(-1, length(levels(ImpData$Var.Names)) + 2)) + 
  theme_light() +
  coord_flip() +
  theme(
    legend.position="bottom",
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_text(size = 8), # Adjust the size of the axis text

  )
```

```{r rf-error}
plot(rf_model)
```