// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package org.prlprg.server.protocol;

public interface BcCompileRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:rsh.server.protocol.BcCompileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 2;</code>
   *
   * @return The name.
   */
  java.lang.String getName();

  /**
   * <code>string name = 2;</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();

  /**
   * <code>bytes closure = 3;</code>
   *
   * @return The closure.
   */
  com.google.protobuf.ByteString getClosure();

  /**
   * <code>uint32 bc_optimization = 4;</code>
   *
   * @return The bcOptimization.
   */
  int getBcOptimization();
}
