// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package org.prlprg.server.protocol;

public interface BcCompileResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:rsh.server.protocol.BcCompileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string failure = 2;</code>
   *
   * @return Whether the failure field is set.
   */
  boolean hasFailure();

  /**
   * <code>string failure = 2;</code>
   *
   * @return The failure.
   */
  java.lang.String getFailure();

  /**
   * <code>string failure = 2;</code>
   *
   * @return The bytes for failure.
   */
  com.google.protobuf.ByteString getFailureBytes();

  /**
   * <code>.rsh.server.protocol.BcCompiledFunction result = 3;</code>
   *
   * @return Whether the result field is set.
   */
  boolean hasResult();

  /**
   * <code>.rsh.server.protocol.BcCompiledFunction result = 3;</code>
   *
   * @return The result.
   */
  org.prlprg.server.protocol.BcCompiledFunction getResult();

  /** <code>.rsh.server.protocol.BcCompiledFunction result = 3;</code> */
  org.prlprg.server.protocol.BcCompiledFunctionOrBuilder getResultOrBuilder();

  public org.prlprg.server.protocol.BcCompileResponse.DataCase getDataCase();
}
