#include <stdint.h>

typedef enum {
BCMISMATCH_BCOP = 0,
RETURN_BCOP = 1,
GOTO_BCOP = 2,
BRIFNOT_BCOP = 3,
POP_BCOP = 4,
DUP_BCOP = 5,
PRINTVALUE_BCOP = 6,
STARTLOOPCNTXT_BCOP = 7,
ENDLOOPCNTXT_BCOP = 8,
DOLOOPNEXT_BCOP = 9,
DOLOOPBREAK_BCOP = 10,
STARTFOR_BCOP = 11,
STEPFOR_BCOP = 12,
ENDFOR_BCOP = 13,
SETLOOPVAL_BCOP = 14,
INVISIBLE_BCOP = 15,
LDCONST_BCOP = 16,
LDNULL_BCOP = 17,
LDTRUE_BCOP = 18,
LDFALSE_BCOP = 19,
GETVAR_BCOP = 20,
DDVAL_BCOP = 21,
SETVAR_BCOP = 22,
GETFUN_BCOP = 23,
GETGLOBFUN_BCOP = 24,
GETSYMFUN_BCOP = 25,
GETBUILTIN_BCOP = 26,
GETINTLBUILTIN_BCOP = 27,
CHECKFUN_BCOP = 28,
MAKEPROM_BCOP = 29,
DOMISSING_BCOP = 30,
SETTAG_BCOP = 31,
DODOTS_BCOP = 32,
PUSHARG_BCOP = 33,
PUSHCONSTARG_BCOP = 34,
PUSHNULLARG_BCOP = 35,
PUSHTRUEARG_BCOP = 36,
PUSHFALSEARG_BCOP = 37,
CALL_BCOP = 38,
CALLBUILTIN_BCOP = 39,
CALLSPECIAL_BCOP = 40,
MAKECLOSURE_BCOP = 41,
UMINUS_BCOP = 42,
UPLUS_BCOP = 43,
ADD_BCOP = 44,
SUB_BCOP = 45,
MUL_BCOP = 46,
DIV_BCOP = 47,
EXPT_BCOP = 48,
SQRT_BCOP = 49,
EXP_BCOP = 50,
EQ_BCOP = 51,
NE_BCOP = 52,
LT_BCOP = 53,
LE_BCOP = 54,
GE_BCOP = 55,
GT_BCOP = 56,
AND_BCOP = 57,
OR_BCOP = 58,
NOT_BCOP = 59,
DOTSERR_BCOP = 60,
STARTASSIGN_BCOP = 61,
ENDASSIGN_BCOP = 62,
STARTSUBSET_BCOP = 63,
DFLTSUBSET_BCOP = 64,
STARTSUBASSIGN_BCOP = 65,
DFLTSUBASSIGN_BCOP = 66,
STARTC_BCOP = 67,
DFLTC_BCOP = 68,
STARTSUBSET2_BCOP = 69,
DFLTSUBSET2_BCOP = 70,
STARTSUBASSIGN2_BCOP = 71,
DFLTSUBASSIGN2_BCOP = 72,
DOLLAR_BCOP = 73,
DOLLARGETS_BCOP = 74,
ISNULL_BCOP = 75,
ISLOGICAL_BCOP = 76,
ISINTEGER_BCOP = 77,
ISDOUBLE_BCOP = 78,
ISCOMPLEX_BCOP = 79,
ISCHARACTER_BCOP = 80,
ISSYMBOL_BCOP = 81,
ISOBJECT_BCOP = 82,
ISNUMERIC_BCOP = 83,
VECSUBSET_BCOP = 84,
MATSUBSET_BCOP = 85,
VECSUBASSIGN_BCOP = 86,
MATSUBASSIGN_BCOP = 87,
AND1ST_BCOP = 88,
AND2ND_BCOP = 89,
OR1ST_BCOP = 90,
OR2ND_BCOP = 91,
GETVAR_MISSOK_BCOP = 92,
DDVAL_MISSOK_BCOP = 93,
VISIBLE_BCOP = 94,
SETVAR2_BCOP = 95,
STARTASSIGN2_BCOP = 96,
ENDASSIGN2_BCOP = 97,
SETTER_CALL_BCOP = 98,
GETTER_CALL_BCOP = 99,
SWAP_BCOP = 100,
DUP2ND_BCOP = 101,
SWITCH_BCOP = 102,
RETURNJMP_BCOP = 103,
STARTSUBSET_N_BCOP = 104,
STARTSUBASSIGN_N_BCOP = 105,
VECSUBSET2_BCOP = 106,
MATSUBSET2_BCOP = 107,
VECSUBASSIGN2_BCOP = 108,
MATSUBASSIGN2_BCOP = 109,
STARTSUBSET2_N_BCOP = 110,
STARTSUBASSIGN2_N_BCOP = 111,
SUBSET_N_BCOP = 112,
SUBSET2_N_BCOP = 113,
SUBASSIGN_N_BCOP = 114,
SUBASSIGN2_N_BCOP = 115,
LOG_BCOP = 116,
LOGBASE_BCOP = 117,
MATH1_BCOP = 118,
DOTCALL_BCOP = 119,
COLON_BCOP = 120,
SEQALONG_BCOP = 121,
SEQLEN_BCOP = 122,
BASEGUARD_BCOP = 123,
INCLNK_BCOP = 124,
DECLNK_BCOP = 125,
DECLNK_N_BCOP = 126,
INCLNKSTK_BCOP = 127,
DECLNKSTK_BCOP = 128
} RCP_BC_OPCODES;

static uint8_t RCP_BC_ARG_CNT[] __attribute__((unused)) = {
/*BCMISMATCH.OP*/ 0,
/*RETURN.OP*/ 0,
/*GOTO.OP*/ 1,
/*BRIFNOT.OP*/ 2,
/*POP.OP*/ 0,
/*DUP.OP*/ 0,
/*PRINTVALUE.OP*/ 0,
/*STARTLOOPCNTXT.OP*/ 2,
/*ENDLOOPCNTXT.OP*/ 1,
/*DOLOOPNEXT.OP*/ 0,
/*DOLOOPBREAK.OP*/ 0,
/*STARTFOR.OP*/ 3,
/*STEPFOR.OP*/ 1,
/*ENDFOR.OP*/ 0,
/*SETLOOPVAL.OP*/ 0,
/*INVISIBLE.OP*/ 0,
/*LDCONST.OP*/ 1,
/*LDNULL.OP*/ 0,
/*LDTRUE.OP*/ 0,
/*LDFALSE.OP*/ 0,
/*GETVAR.OP*/ 1,
/*DDVAL.OP*/ 1,
/*SETVAR.OP*/ 1,
/*GETFUN.OP*/ 1,
/*GETGLOBFUN.OP*/ 1,
/*GETSYMFUN.OP*/ 1,
/*GETBUILTIN.OP*/ 1,
/*GETINTLBUILTIN.OP*/ 1,
/*CHECKFUN.OP*/ 0,
/*MAKEPROM.OP*/ 1,
/*DOMISSING.OP*/ 0,
/*SETTAG.OP*/ 1,
/*DODOTS.OP*/ 0,
/*PUSHARG.OP*/ 0,
/*PUSHCONSTARG.OP*/ 1,
/*PUSHNULLARG.OP*/ 0,
/*PUSHTRUEARG.OP*/ 0,
/*PUSHFALSEARG.OP*/ 0,
/*CALL.OP*/ 1,
/*CALLBUILTIN.OP*/ 1,
/*CALLSPECIAL.OP*/ 1,
/*MAKECLOSURE.OP*/ 1,
/*UMINUS.OP*/ 1,
/*UPLUS.OP*/ 1,
/*ADD.OP*/ 1,
/*SUB.OP*/ 1,
/*MUL.OP*/ 1,
/*DIV.OP*/ 1,
/*EXPT.OP*/ 1,
/*SQRT.OP*/ 1,
/*EXP.OP*/ 1,
/*EQ.OP*/ 1,
/*NE.OP*/ 1,
/*LT.OP*/ 1,
/*LE.OP*/ 1,
/*GE.OP*/ 1,
/*GT.OP*/ 1,
/*AND.OP*/ 1,
/*OR.OP*/ 1,
/*NOT.OP*/ 1,
/*DOTSERR.OP*/ 0,
/*STARTASSIGN.OP*/ 1,
/*ENDASSIGN.OP*/ 1,
/*STARTSUBSET.OP*/ 2,
/*DFLTSUBSET.OP*/ 0,
/*STARTSUBASSIGN.OP*/ 2,
/*DFLTSUBASSIGN.OP*/ 0,
/*STARTC.OP*/ 2,
/*DFLTC.OP*/ 0,
/*STARTSUBSET2.OP*/ 2,
/*DFLTSUBSET2.OP*/ 0,
/*STARTSUBASSIGN2.OP*/ 2,
/*DFLTSUBASSIGN2.OP*/ 0,
/*DOLLAR.OP*/ 2,
/*DOLLARGETS.OP*/ 2,
/*ISNULL.OP*/ 0,
/*ISLOGICAL.OP*/ 0,
/*ISINTEGER.OP*/ 0,
/*ISDOUBLE.OP*/ 0,
/*ISCOMPLEX.OP*/ 0,
/*ISCHARACTER.OP*/ 0,
/*ISSYMBOL.OP*/ 0,
/*ISOBJECT.OP*/ 0,
/*ISNUMERIC.OP*/ 0,
/*VECSUBSET.OP*/ 1,
/*MATSUBSET.OP*/ 1,
/*VECSUBASSIGN.OP*/ 1,
/*MATSUBASSIGN.OP*/ 1,
/*AND1ST.OP*/ 2,
/*AND2ND.OP*/ 1,
/*OR1ST.OP*/ 2,
/*OR2ND.OP*/ 1,
/*GETVAR_MISSOK.OP*/ 1,
/*DDVAL_MISSOK.OP*/ 1,
/*VISIBLE.OP*/ 0,
/*SETVAR2.OP*/ 1,
/*STARTASSIGN2.OP*/ 1,
/*ENDASSIGN2.OP*/ 1,
/*SETTER_CALL.OP*/ 2,
/*GETTER_CALL.OP*/ 1,
/*SWAP.OP*/ 0,
/*DUP2ND.OP*/ 0,
/*SWITCH.OP*/ 4,
/*RETURNJMP.OP*/ 0,
/*STARTSUBSET_N.OP*/ 2,
/*STARTSUBASSIGN_N.OP*/ 2,
/*VECSUBSET2.OP*/ 1,
/*MATSUBSET2.OP*/ 1,
/*VECSUBASSIGN2.OP*/ 1,
/*MATSUBASSIGN2.OP*/ 1,
/*STARTSUBSET2_N.OP*/ 2,
/*STARTSUBASSIGN2_N.OP*/ 2,
/*SUBSET_N.OP*/ 2,
/*SUBSET2_N.OP*/ 2,
/*SUBASSIGN_N.OP*/ 2,
/*SUBASSIGN2_N.OP*/ 2,
/*LOG.OP*/ 1,
/*LOGBASE.OP*/ 1,
/*MATH1.OP*/ 2,
/*DOTCALL.OP*/ 2,
/*COLON.OP*/ 1,
/*SEQALONG.OP*/ 1,
/*SEQLEN.OP*/ 1,
/*BASEGUARD.OP*/ 2,
/*INCLNK.OP*/ 0,
/*DECLNK.OP*/ 0,
/*DECLNK_N.OP*/ 1,
/*INCLNKSTK.OP*/ 0,
/*DECLNKSTK.OP*/ 0
};

#define RCP_BC_STACK_EFFECT_BCMISMATCH 0
#define RCP_BC_STACK_EFFECT_RETURN -1
#define RCP_BC_STACK_EFFECT_GOTO 0
#define RCP_BC_STACK_EFFECT_BRIFNOT -1
#define RCP_BC_STACK_EFFECT_POP -1
#define RCP_BC_STACK_EFFECT_DUP 1
#define RCP_BC_STACK_EFFECT_PRINTVALUE 0
#define RCP_BC_STACK_EFFECT_STARTLOOPCNTXT 0
#define RCP_BC_STACK_EFFECT_ENDLOOPCNTXT 0
#define RCP_BC_STACK_EFFECT_DOLOOPNEXT 0
#define RCP_BC_STACK_EFFECT_DOLOOPBREAK 0
#define RCP_BC_STACK_EFFECT_STARTFOR 2
#define RCP_BC_STACK_EFFECT_STEPFOR 0
#define RCP_BC_STACK_EFFECT_ENDFOR -2
#define RCP_BC_STACK_EFFECT_SETLOOPVAL 0
#define RCP_BC_STACK_EFFECT_INVISIBLE 0
#define RCP_BC_STACK_EFFECT_LDCONST 1
#define RCP_BC_STACK_EFFECT_LDNULL 1
#define RCP_BC_STACK_EFFECT_LDTRUE 1
#define RCP_BC_STACK_EFFECT_LDFALSE 1
#define RCP_BC_STACK_EFFECT_GETVAR 1
#define RCP_BC_STACK_EFFECT_DDVAL 1
#define RCP_BC_STACK_EFFECT_SETVAR 0
#define RCP_BC_STACK_EFFECT_GETFUN 3
#define RCP_BC_STACK_EFFECT_GETGLOBFUN 0
#define RCP_BC_STACK_EFFECT_GETSYMFUN 0
#define RCP_BC_STACK_EFFECT_GETBUILTIN 3
#define RCP_BC_STACK_EFFECT_GETINTLBUILTIN 3
#define RCP_BC_STACK_EFFECT_CHECKFUN 2
#define RCP_BC_STACK_EFFECT_MAKEPROM 0
#define RCP_BC_STACK_EFFECT_DOMISSING 0
#define RCP_BC_STACK_EFFECT_SETTAG 0
#define RCP_BC_STACK_EFFECT_DODOTS 0
#define RCP_BC_STACK_EFFECT_PUSHARG -1
#define RCP_BC_STACK_EFFECT_PUSHCONSTARG 0
#define RCP_BC_STACK_EFFECT_PUSHNULLARG 0
#define RCP_BC_STACK_EFFECT_PUSHTRUEARG 0
#define RCP_BC_STACK_EFFECT_PUSHFALSEARG 0
#define RCP_BC_STACK_EFFECT_CALL -2
#define RCP_BC_STACK_EFFECT_CALLBUILTIN -2
#define RCP_BC_STACK_EFFECT_CALLSPECIAL 1
#define RCP_BC_STACK_EFFECT_MAKECLOSURE 1
#define RCP_BC_STACK_EFFECT_UMINUS 0
#define RCP_BC_STACK_EFFECT_UPLUS 0
#define RCP_BC_STACK_EFFECT_ADD -1
#define RCP_BC_STACK_EFFECT_SUB -1
#define RCP_BC_STACK_EFFECT_MUL -1
#define RCP_BC_STACK_EFFECT_DIV -1
#define RCP_BC_STACK_EFFECT_EXPT -1
#define RCP_BC_STACK_EFFECT_SQRT 0
#define RCP_BC_STACK_EFFECT_EXP 0
#define RCP_BC_STACK_EFFECT_EQ -1
#define RCP_BC_STACK_EFFECT_NE -1
#define RCP_BC_STACK_EFFECT_LT -1
#define RCP_BC_STACK_EFFECT_LE -1
#define RCP_BC_STACK_EFFECT_GE -1
#define RCP_BC_STACK_EFFECT_GT -1
#define RCP_BC_STACK_EFFECT_AND -1
#define RCP_BC_STACK_EFFECT_OR -1
#define RCP_BC_STACK_EFFECT_NOT 0
#define RCP_BC_STACK_EFFECT_DOTSERR 0
#define RCP_BC_STACK_EFFECT_STARTASSIGN 3
#define RCP_BC_STACK_EFFECT_ENDASSIGN -2
#define RCP_BC_STACK_EFFECT_STARTSUBSET 3
#define RCP_BC_STACK_EFFECT_DFLTSUBSET -3
#define RCP_BC_STACK_EFFECT_STARTSUBASSIGN 3
#define RCP_BC_STACK_EFFECT_DFLTSUBASSIGN -4
#define RCP_BC_STACK_EFFECT_STARTC 0
#define RCP_BC_STACK_EFFECT_DFLTC 0
#define RCP_BC_STACK_EFFECT_STARTSUBSET2 3
#define RCP_BC_STACK_EFFECT_DFLTSUBSET2 -3
#define RCP_BC_STACK_EFFECT_STARTSUBASSIGN2 3
#define RCP_BC_STACK_EFFECT_DFLTSUBASSIGN2 -4
#define RCP_BC_STACK_EFFECT_DOLLAR 0
#define RCP_BC_STACK_EFFECT_DOLLARGETS -1
#define RCP_BC_STACK_EFFECT_ISNULL 0
#define RCP_BC_STACK_EFFECT_ISLOGICAL 0
#define RCP_BC_STACK_EFFECT_ISINTEGER 0
#define RCP_BC_STACK_EFFECT_ISDOUBLE 0
#define RCP_BC_STACK_EFFECT_ISCOMPLEX 0
#define RCP_BC_STACK_EFFECT_ISCHARACTER 0
#define RCP_BC_STACK_EFFECT_ISSYMBOL 0
#define RCP_BC_STACK_EFFECT_ISOBJECT 0
#define RCP_BC_STACK_EFFECT_ISNUMERIC 0
#define RCP_BC_STACK_EFFECT_VECSUBSET -1
#define RCP_BC_STACK_EFFECT_MATSUBSET -2
#define RCP_BC_STACK_EFFECT_VECSUBASSIGN -2
#define RCP_BC_STACK_EFFECT_MATSUBASSIGN -3
#define RCP_BC_STACK_EFFECT_AND1ST 0
#define RCP_BC_STACK_EFFECT_AND2ND -1
#define RCP_BC_STACK_EFFECT_OR1ST 0
#define RCP_BC_STACK_EFFECT_OR2ND -1
#define RCP_BC_STACK_EFFECT_GETVAR_MISSOK 1
#define RCP_BC_STACK_EFFECT_DDVAL_MISSOK 1
#define RCP_BC_STACK_EFFECT_VISIBLE 0
#define RCP_BC_STACK_EFFECT_SETVAR2 0
#define RCP_BC_STACK_EFFECT_STARTASSIGN2 3
#define RCP_BC_STACK_EFFECT_ENDASSIGN2 -2
#define RCP_BC_STACK_EFFECT_SETTER_CALL -4
#define RCP_BC_STACK_EFFECT_GETTER_CALL -2
#define RCP_BC_STACK_EFFECT_SWAP 0
#define RCP_BC_STACK_EFFECT_DUP2ND 1
#define RCP_BC_STACK_EFFECT_SWITCH -1
#define RCP_BC_STACK_EFFECT_RETURNJMP -1
#define RCP_BC_STACK_EFFECT_STARTSUBSET_N 0
#define RCP_BC_STACK_EFFECT_STARTSUBASSIGN_N 0
#define RCP_BC_STACK_EFFECT_VECSUBSET2 -1
#define RCP_BC_STACK_EFFECT_MATSUBSET2 -2
#define RCP_BC_STACK_EFFECT_VECSUBASSIGN2 -2
#define RCP_BC_STACK_EFFECT_MATSUBASSIGN2 -3
#define RCP_BC_STACK_EFFECT_STARTSUBSET2_N 0
#define RCP_BC_STACK_EFFECT_STARTSUBASSIGN2_N 0
#define RCP_BC_STACK_EFFECT_SUBSET_N 0
#define RCP_BC_STACK_EFFECT_SUBSET2_N 0
#define RCP_BC_STACK_EFFECT_SUBASSIGN_N -1
#define RCP_BC_STACK_EFFECT_SUBASSIGN2_N -1
#define RCP_BC_STACK_EFFECT_LOG 0
#define RCP_BC_STACK_EFFECT_LOGBASE -1
#define RCP_BC_STACK_EFFECT_MATH1 0
#define RCP_BC_STACK_EFFECT_DOTCALL 0
#define RCP_BC_STACK_EFFECT_COLON -1
#define RCP_BC_STACK_EFFECT_SEQALONG 0
#define RCP_BC_STACK_EFFECT_SEQLEN 0
#define RCP_BC_STACK_EFFECT_BASEGUARD 0
#define RCP_BC_STACK_EFFECT_INCLNK 0
#define RCP_BC_STACK_EFFECT_DECLNK 0
#define RCP_BC_STACK_EFFECT_DECLNK_N 0
#define RCP_BC_STACK_EFFECT_INCLNKSTK 1
#define RCP_BC_STACK_EFFECT_DECLNKSTK -1

static int8_t RCP_BC_STACK_EFFECT[] __attribute__((unused)) = {
    RCP_BC_STACK_EFFECT_BCMISMATCH,
    RCP_BC_STACK_EFFECT_RETURN,
    RCP_BC_STACK_EFFECT_GOTO,
    RCP_BC_STACK_EFFECT_BRIFNOT,
    RCP_BC_STACK_EFFECT_POP,
    RCP_BC_STACK_EFFECT_DUP,
    RCP_BC_STACK_EFFECT_PRINTVALUE,
    RCP_BC_STACK_EFFECT_STARTLOOPCNTXT,
    RCP_BC_STACK_EFFECT_ENDLOOPCNTXT,
    RCP_BC_STACK_EFFECT_DOLOOPNEXT,
    RCP_BC_STACK_EFFECT_DOLOOPBREAK,
    RCP_BC_STACK_EFFECT_STARTFOR,
    RCP_BC_STACK_EFFECT_STEPFOR,
    RCP_BC_STACK_EFFECT_ENDFOR,
    RCP_BC_STACK_EFFECT_SETLOOPVAL,
    RCP_BC_STACK_EFFECT_INVISIBLE,
    RCP_BC_STACK_EFFECT_LDCONST,
    RCP_BC_STACK_EFFECT_LDNULL,
    RCP_BC_STACK_EFFECT_LDTRUE,
    RCP_BC_STACK_EFFECT_LDFALSE,
    RCP_BC_STACK_EFFECT_GETVAR,
    RCP_BC_STACK_EFFECT_DDVAL,
    RCP_BC_STACK_EFFECT_SETVAR,
    RCP_BC_STACK_EFFECT_GETFUN,
    RCP_BC_STACK_EFFECT_GETGLOBFUN,
    RCP_BC_STACK_EFFECT_GETSYMFUN,
    RCP_BC_STACK_EFFECT_GETBUILTIN,
    RCP_BC_STACK_EFFECT_GETINTLBUILTIN,
    RCP_BC_STACK_EFFECT_CHECKFUN,
    RCP_BC_STACK_EFFECT_MAKEPROM,
    RCP_BC_STACK_EFFECT_DOMISSING,
    RCP_BC_STACK_EFFECT_SETTAG,
    RCP_BC_STACK_EFFECT_DODOTS,
    RCP_BC_STACK_EFFECT_PUSHARG,
    RCP_BC_STACK_EFFECT_PUSHCONSTARG,
    RCP_BC_STACK_EFFECT_PUSHNULLARG,
    RCP_BC_STACK_EFFECT_PUSHTRUEARG,
    RCP_BC_STACK_EFFECT_PUSHFALSEARG,
    RCP_BC_STACK_EFFECT_CALL,
    RCP_BC_STACK_EFFECT_CALLBUILTIN,
    RCP_BC_STACK_EFFECT_CALLSPECIAL,
    RCP_BC_STACK_EFFECT_MAKECLOSURE,
    RCP_BC_STACK_EFFECT_UMINUS,
    RCP_BC_STACK_EFFECT_UPLUS,
    RCP_BC_STACK_EFFECT_ADD,
    RCP_BC_STACK_EFFECT_SUB,
    RCP_BC_STACK_EFFECT_MUL,
    RCP_BC_STACK_EFFECT_DIV,
    RCP_BC_STACK_EFFECT_EXPT,
    RCP_BC_STACK_EFFECT_SQRT,
    RCP_BC_STACK_EFFECT_EXP,
    RCP_BC_STACK_EFFECT_EQ,
    RCP_BC_STACK_EFFECT_NE,
    RCP_BC_STACK_EFFECT_LT,
    RCP_BC_STACK_EFFECT_LE,
    RCP_BC_STACK_EFFECT_GE,
    RCP_BC_STACK_EFFECT_GT,
    RCP_BC_STACK_EFFECT_AND,
    RCP_BC_STACK_EFFECT_OR,
    RCP_BC_STACK_EFFECT_NOT,
    RCP_BC_STACK_EFFECT_DOTSERR,
    RCP_BC_STACK_EFFECT_STARTASSIGN,
    RCP_BC_STACK_EFFECT_ENDASSIGN,
    RCP_BC_STACK_EFFECT_STARTSUBSET,
    RCP_BC_STACK_EFFECT_DFLTSUBSET,
    RCP_BC_STACK_EFFECT_STARTSUBASSIGN,
    RCP_BC_STACK_EFFECT_DFLTSUBASSIGN,
    RCP_BC_STACK_EFFECT_STARTC,
    RCP_BC_STACK_EFFECT_DFLTC,
    RCP_BC_STACK_EFFECT_STARTSUBSET2,
    RCP_BC_STACK_EFFECT_DFLTSUBSET2,
    RCP_BC_STACK_EFFECT_STARTSUBASSIGN2,
    RCP_BC_STACK_EFFECT_DFLTSUBASSIGN2,
    RCP_BC_STACK_EFFECT_DOLLAR,
    RCP_BC_STACK_EFFECT_DOLLARGETS,
    RCP_BC_STACK_EFFECT_ISNULL,
    RCP_BC_STACK_EFFECT_ISLOGICAL,
    RCP_BC_STACK_EFFECT_ISINTEGER,
    RCP_BC_STACK_EFFECT_ISDOUBLE,
    RCP_BC_STACK_EFFECT_ISCOMPLEX,
    RCP_BC_STACK_EFFECT_ISCHARACTER,
    RCP_BC_STACK_EFFECT_ISSYMBOL,
    RCP_BC_STACK_EFFECT_ISOBJECT,
    RCP_BC_STACK_EFFECT_ISNUMERIC,
    RCP_BC_STACK_EFFECT_VECSUBSET,
    RCP_BC_STACK_EFFECT_MATSUBSET,
    RCP_BC_STACK_EFFECT_VECSUBASSIGN,
    RCP_BC_STACK_EFFECT_MATSUBASSIGN,
    RCP_BC_STACK_EFFECT_AND1ST,
    RCP_BC_STACK_EFFECT_AND2ND,
    RCP_BC_STACK_EFFECT_OR1ST,
    RCP_BC_STACK_EFFECT_OR2ND,
    RCP_BC_STACK_EFFECT_GETVAR_MISSOK,
    RCP_BC_STACK_EFFECT_DDVAL_MISSOK,
    RCP_BC_STACK_EFFECT_VISIBLE,
    RCP_BC_STACK_EFFECT_SETVAR2,
    RCP_BC_STACK_EFFECT_STARTASSIGN2,
    RCP_BC_STACK_EFFECT_ENDASSIGN2,
    RCP_BC_STACK_EFFECT_SETTER_CALL,
    RCP_BC_STACK_EFFECT_GETTER_CALL,
    RCP_BC_STACK_EFFECT_SWAP,
    RCP_BC_STACK_EFFECT_DUP2ND,
    RCP_BC_STACK_EFFECT_SWITCH,
    RCP_BC_STACK_EFFECT_RETURNJMP,
    RCP_BC_STACK_EFFECT_STARTSUBSET_N,
    RCP_BC_STACK_EFFECT_STARTSUBASSIGN_N,
    RCP_BC_STACK_EFFECT_VECSUBSET2,
    RCP_BC_STACK_EFFECT_MATSUBSET2,
    RCP_BC_STACK_EFFECT_VECSUBASSIGN2,
    RCP_BC_STACK_EFFECT_MATSUBASSIGN2,
    RCP_BC_STACK_EFFECT_STARTSUBSET2_N,
    RCP_BC_STACK_EFFECT_STARTSUBASSIGN2_N,
    RCP_BC_STACK_EFFECT_SUBSET_N,
    RCP_BC_STACK_EFFECT_SUBSET2_N,
    RCP_BC_STACK_EFFECT_SUBASSIGN_N,
    RCP_BC_STACK_EFFECT_SUBASSIGN2_N,
    RCP_BC_STACK_EFFECT_LOG,
    RCP_BC_STACK_EFFECT_LOGBASE,
    RCP_BC_STACK_EFFECT_MATH1,
    RCP_BC_STACK_EFFECT_DOTCALL,
    RCP_BC_STACK_EFFECT_COLON,
    RCP_BC_STACK_EFFECT_SEQALONG,
    RCP_BC_STACK_EFFECT_SEQLEN,
    RCP_BC_STACK_EFFECT_BASEGUARD,
    RCP_BC_STACK_EFFECT_INCLNK,
    RCP_BC_STACK_EFFECT_DECLNK,
    RCP_BC_STACK_EFFECT_DECLNK_N,
    RCP_BC_STACK_EFFECT_INCLNKSTK,
    RCP_BC_STACK_EFFECT_DECLNKSTK
};
