FROM ghcr.io/prl-prg/rcp-base

ARG RSH_COMMIT

RUN git config --global url."https://github.com/".insteadOf git@github.com:

RUN git clone git@github.com:PRL-PRG/r-compile-server.git /rsh && \
    git -C /rsh checkout --detach ${RSH_COMMIT} && \
    git -C /rsh submodule update --init --depth 1 external/R

RUN cd /rsh && \
    bash -x ./tools/build-gnur.sh external/R

ENV R_HOME=/rsh/external/R
ENV PATH="${PATH}:${R_HOME}/bin"
