#? stdlib
`tidy_validate_package_Rd_files_from_dir` <- function (dir, auto = NA, verbose) 
{
    if (!length(dir)) 
        return(NULL)
    out <- tempfile()
    on.exit(unlink(out))
    one <- function(d) {
        if (verbose) 
            message(sprintf("* Package: %s", basename(d)))
        db <- Rd_db(dir = d)
        if (!is.na(auto)) {
            is <- vapply(db, function(e) {
                g <- attr(e, "meta")$generator
                (is.character(g) && (length(g) == 1L) && startsWith(g, 
                  "% Generated by roxygen2"))
            }, NA)
            db <- db[if (auto) 
                is
            else !is]
        }
        results <- lapply(db, function(x) {
            tryCatch({
                Rd2HTML(x, out, concordance = TRUE)
                tidy_validate(out)
            }, error = identity)
        })
        tidy_validate_db(results, sprintf("%s::%s", basename(d), 
            names(db)))
    }
    do.call(rbind, lapply(dir, one))
}
