#? stdlib
`.Rd_get_offending_autogenerated_content` <- function (x) 
{
    out <- NULL
    s <- .Rd_get_section(x, "title")
    if (length(s)) {
        s <- .Rd_deparse(s, tag = FALSE)
        if (startsWith(trimws(s), "A Capitalized Title")) 
            out <- rbind(out, c("\\title", s))
    }
    s <- .Rd_get_section(x, "details")
    if (length(s)) {
        s <- .Rd_deparse(.Rd_drop_comments(s), tag = FALSE)
        if (grepl("If necessary, more details than the description above", 
            s, fixed = TRUE)) 
            out <- rbind(out, c("\\details", s))
    }
    tab <- .Rd_get_argument_table(x)
    if (length(tab)) {
        descs <- trimws(tab[, 2L])
        ind <- descs == sprintf("~~Describe \\code{%s} here~~", 
            tab[, 1L])
        if (any(ind)) 
            out <- rbind(out, cbind(sprintf("\\arguments: %s", 
                tab[ind, 1L]), tab[ind, 2L]))
    }
    s <- .Rd_get_section(x, "details")
    if (length(s) && length(s) <= 11 && any(grepl("~~ An overview of how to use the package", 
        unlist(s[RdTags(s) == "TEXT"]), fixed = TRUE))) 
        out <- rbind(out, c("\\details", .Rd_deparse(s, tag = FALSE)))
    s <- .Rd_get_section(x, "references")
    if (length(s)) {
        s <- .Rd_deparse(.Rd_drop_comments(s), tag = FALSE)
        if (grepl("[Ll]iterature or other references for background information", 
            gsub("[[:space:]]+", " ", s))) 
            out <- rbind(out, c("\\references", s))
    }
    s <- .Rd_get_section(x, "seealso")
    if (length(s) && length(s) <= 5) {
        s <- .Rd_deparse(.Rd_drop_comments(s), tag = FALSE)
        if (grepl("Optional links to other man pages", s, fixed = TRUE)) 
            out <- rbind(out, c("\\seealso", s))
    }
    s <- .Rd_get_section(x, "examples")
    if (length(s)) {
        s <- .Rd_deparse(.Rd_drop_comments(s), tag = FALSE)
        if (grepl("Optional simple examples of the most important functions", 
            s, fixed = TRUE)) 
            out <- rbind(out, c("\\examples", s))
    }
    tab <- .Rd_get_methods_description_table(x)
    if (length(tab)) {
        descriptions <- trimws(tab[, 2L])
        ind <- descriptions == "~~describe this method here"
        if (any(ind)) 
            out <- rbind(out, cbind(sprintf("section 'Methods', description of item '%s'", 
                tab[ind, 1L]), tab[ind, 2L]))
    }
    if (config_val_to_logical(Sys.getenv("_R_CHECK_RD_CONTENTS_KEYWORDS_", 
        "FALSE"))) {
        k <- .Rd_get_metadata(x, "keyword")
        k <- k[k %in% .Rd_keywords_auto]
        if (length(k)) {
            out <- rbind(out, cbind("\\keyword", k))
        }
    }
    out
}
