#? stdlib
`prepare2_Rd` <- function (Rd, Rdfile, stages) 
{
    sections <- RdTags(Rd)
    version <- which(sections == "\\Rdversion")
    if (length(version) > 1L) 
        stopRd(Rd[[version[2L]]], Rdfile, "Only one \\Rdversion declaration is allowed")
    if (length(bad <- grep("[^[:blank:][:cntrl:]]", unlist(Rd[sections == 
        "TEXT"]), perl = TRUE, useBytes = TRUE))) 
        for (s in bad) warnRd(Rd[sections == "TEXT"][[s]], Rdfile, 
            "All text must be in a section")
    drop <- rep.int(FALSE, length(sections))
    unique_tags <- paste0("\\", c("description", "usage", "arguments", 
        "format", "details", "value", "references", "source", 
        "seealso", "examples", "author", "encoding"))
    for (tag in unique_tags) {
        where <- which(sections == tag)
        if (length(where) > 1L) {
            warnRd(NULL, Rdfile, sprintf("Only one %s section is allowed: the first will be used", 
                tag))
            drop[where[-1L]] <- TRUE
        }
    }
    enc <- which(sections == "\\encoding")
    if (length(enc)) {
        encoding <- Rd[[enc[1L]]]
        if (!identical(RdTags(encoding), "TEXT")) 
            stopRd(encoding, Rdfile, "'encoding' must be plain text")
    }
    dt <- which(sections == "\\docType")
    docTypes <- character(length(dt))
    if (length(dt)) {
        if (length(dt) > 1L) 
            warnRd(NULL, Rdfile, "Multiple \\docType sections are not supported")
        for (i in seq_along(dt)) {
            docType <- Rd[[dt[i]]]
            if (!identical(RdTags(docType), "TEXT")) 
                stopRd(docType, Rdfile, "'docType' must be plain text")
            docTypes[i] <- sub("^ *", "", sub(" *$", "", docType[[1L]]))
            if (docTypes[i] %notin% c("data", "package", "methods", 
                "class", "import")) 
                warnRd(docType, Rdfile, "docType ", sQuote(docTypes[i]), 
                  " is unrecognized")
        }
    }
    generator <- if ((sections[1L] == "COMMENT") && startsWith(Rd[[1L]], 
        "% Generated by")) 
        c(Rd[[1L]])
    else ""
    extras <- c("COMMENT", "TEXT", "\\docType", "\\Rdversion", 
        "\\RdOpts", "USERMACRO", "\\newcommand", "\\renewcommand")
    drop <- drop | (sections %in% extras)
    bad <- sections %notin% c(names(sectionOrder), extras)
    if ("render" %notin% stages) {
        render <- vapply(Rd, function(r) getDynamicFlags(r)[["render"]], 
            TRUE)
        bad <- bad & (sections != "\\Sexpr" | !render)
    }
    if (any(bad)) {
        for (s in which(bad)) warnRd(Rd[[s]], Rdfile, "Section ", 
            sections[s], " is unrecognized and will be dropped")
        drop <- drop | bad
    }
    Rd <- Rd[!drop]
    sections <- sections[!drop]
    sortorder <- order(sectionOrder[sections])
    Rd <- Rd[sortorder]
    sections <- sections[sortorder]
    if (!identical(sections[1:2], c("\\title", "\\name")) || 
        identical(sections[3L], "\\name")) 
        stopRd(NULL, Rdfile, "Sections \\title, and \\name must exist and be unique in Rd files")
    if (length(Rd[[2L]]) != 1L || grepl("\\", Rd[[2L]][[1L]], 
        fixed = TRUE)) 
        stopRd(Rd[[2L]], Rdfile, "\\name must only contain simple text")
    structure(Rd, meta = list(docType = docTypes, generator = generator))
}
