#? stdlib
`checkRdContents` <- function (package, dir, lib.loc = NULL, chkInternal = NULL) 
{
    out <- list()
    class(out) <- "checkRdContents"
    if (!missing(package)) {
        if (length(package) != 1L) 
            stop("argument 'package' must be of length 1")
        dir <- find.package(package, lib.loc)
    }
    else {
        if (missing(dir)) 
            stop("you must specify 'package' or 'dir'")
        if (!dir.exists(dir)) 
            stop(gettextf("directory '%s' does not exist", dir), 
                domain = NA)
        else dir <- file_path_as_absolute(dir)
    }
    check_internal_specially <- FALSE
    if (is.null(chkInternal) || !is.logical(chkInternal) || (length(chkInternal) != 
        1L) || is.na(chkInternal)) 
        chkInternal <- check_internal_specially <- TRUE
    db <- if (!missing(package)) 
        Rd_db(package, lib.loc = dirname(dir))
    else Rd_db(dir = dir)
    for (nm in names(db)) {
        rd <- db[[nm]]
        internal <- "internal" %in% .Rd_get_metadata(rd, "keyword")
        if (internal && !chkInternal) 
            next
        special <- (internal && check_internal_specially)
        missing_description <- !identical("package", .Rd_get_doc_type(rd)) && 
            "\\description" %notin% RdTags(rd)
        arguments_with_no_description <- if (special) 
            NULL
        else {
            arg_table <- .Rd_get_argument_table(rd)
            arg_table[grepl("^[[:space:]]*$", arg_table[, 2L]), 
                1L]
        }
        offending_autogenerated_content <- .Rd_get_offending_autogenerated_content(rd)
        if (missing_description || length(arguments_with_no_description) || 
            length(offending_autogenerated_content)) {
            out[[nm]] <- list(missing_description = missing_description, 
                arguments_with_no_description = arguments_with_no_description, 
                offending_autogenerated_content = offending_autogenerated_content)
        }
    }
    out
}
