// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package org.prlprg.server.protocol;

public interface CompileRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:rsh.server.protocol.CompileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 2;</code>
   *
   * @return The name.
   */
  java.lang.String getName();

  /**
   * <code>string name = 2;</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();

  /**
   *
   *
   * <pre>
   * the closure to be compiled as CLOSXP
   * </pre>
   *
   * <code>bytes closure = 3;</code>
   *
   * @return The closure.
   */
  com.google.protobuf.ByteString getClosure();
}
