// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package org.prlprg.server.protocol;

/**
 * Protobuf type {@code rsh.server.protocol.CompileResponse}
 */
public final class CompileResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rsh.server.protocol.CompileResponse)
    CompileResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CompileResponse.newBuilder() to construct.
  private CompileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CompileResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CompileResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CompileResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            dataCase_ = 2;
            data_ = s;
            break;
          }
          case 26: {
            org.prlprg.server.protocol.CompiledFunction.Builder subBuilder = null;
            if (dataCase_ == 3) {
              subBuilder = ((org.prlprg.server.protocol.CompiledFunction) data_).toBuilder();
            }
            data_ =
                input.readMessage(org.prlprg.server.protocol.CompiledFunction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.prlprg.server.protocol.CompiledFunction) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.prlprg.server.protocol.Protocol.internal_static_rsh_server_protocol_CompileResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.prlprg.server.protocol.Protocol.internal_static_rsh_server_protocol_CompileResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.prlprg.server.protocol.CompileResponse.class, org.prlprg.server.protocol.CompileResponse.Builder.class);
  }

  private int dataCase_ = 0;
  private java.lang.Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    FAILURE(2),
    RESULT(3),
    DATA_NOT_SET(0);
    private final int value;
    private DataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 2: return FAILURE;
        case 3: return RESULT;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int FAILURE_FIELD_NUMBER = 2;
  /**
   * <code>string failure = 2;</code>
   * @return The failure.
   */
  public java.lang.String getFailure() {
    java.lang.Object ref = "";
    if (dataCase_ == 2) {
      ref = data_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (dataCase_ == 2) {
        data_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string failure = 2;</code>
   * @return The bytes for failure.
   */
  public com.google.protobuf.ByteString
      getFailureBytes() {
    java.lang.Object ref = "";
    if (dataCase_ == 2) {
      ref = data_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (dataCase_ == 2) {
        data_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULT_FIELD_NUMBER = 3;
  /**
   * <code>.rsh.server.protocol.CompiledFunction result = 3;</code>
   * @return Whether the result field is set.
   */
  @java.lang.Override
  public boolean hasResult() {
    return dataCase_ == 3;
  }
  /**
   * <code>.rsh.server.protocol.CompiledFunction result = 3;</code>
   * @return The result.
   */
  @java.lang.Override
  public org.prlprg.server.protocol.CompiledFunction getResult() {
    if (dataCase_ == 3) {
       return (org.prlprg.server.protocol.CompiledFunction) data_;
    }
    return org.prlprg.server.protocol.CompiledFunction.getDefaultInstance();
  }
  /**
   * <code>.rsh.server.protocol.CompiledFunction result = 3;</code>
   */
  @java.lang.Override
  public org.prlprg.server.protocol.CompiledFunctionOrBuilder getResultOrBuilder() {
    if (dataCase_ == 3) {
       return (org.prlprg.server.protocol.CompiledFunction) data_;
    }
    return org.prlprg.server.protocol.CompiledFunction.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
    }
    if (dataCase_ == 3) {
      output.writeMessage(3, (org.prlprg.server.protocol.CompiledFunction) data_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dataCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
    }
    if (dataCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (org.prlprg.server.protocol.CompiledFunction) data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.prlprg.server.protocol.CompileResponse)) {
      return super.equals(obj);
    }
    org.prlprg.server.protocol.CompileResponse other = (org.prlprg.server.protocol.CompileResponse) obj;

    if (!getDataCase().equals(other.getDataCase())) return false;
    switch (dataCase_) {
      case 2:
        if (!getFailure()
            .equals(other.getFailure())) return false;
        break;
      case 3:
        if (!getResult()
            .equals(other.getResult())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (dataCase_) {
      case 2:
        hash = (37 * hash) + FAILURE_FIELD_NUMBER;
        hash = (53 * hash) + getFailure().hashCode();
        break;
      case 3:
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.prlprg.server.protocol.CompileResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.prlprg.server.protocol.CompileResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.prlprg.server.protocol.CompileResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.prlprg.server.protocol.CompileResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.prlprg.server.protocol.CompileResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.prlprg.server.protocol.CompileResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.prlprg.server.protocol.CompileResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.prlprg.server.protocol.CompileResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.prlprg.server.protocol.CompileResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.prlprg.server.protocol.CompileResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.prlprg.server.protocol.CompileResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.prlprg.server.protocol.CompileResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.prlprg.server.protocol.CompileResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rsh.server.protocol.CompileResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rsh.server.protocol.CompileResponse)
      org.prlprg.server.protocol.CompileResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.prlprg.server.protocol.Protocol.internal_static_rsh_server_protocol_CompileResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.prlprg.server.protocol.Protocol.internal_static_rsh_server_protocol_CompileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.prlprg.server.protocol.CompileResponse.class, org.prlprg.server.protocol.CompileResponse.Builder.class);
    }

    // Construct using org.prlprg.server.protocol.CompileResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dataCase_ = 0;
      data_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.prlprg.server.protocol.Protocol.internal_static_rsh_server_protocol_CompileResponse_descriptor;
    }

    @java.lang.Override
    public org.prlprg.server.protocol.CompileResponse getDefaultInstanceForType() {
      return org.prlprg.server.protocol.CompileResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.prlprg.server.protocol.CompileResponse build() {
      org.prlprg.server.protocol.CompileResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.prlprg.server.protocol.CompileResponse buildPartial() {
      org.prlprg.server.protocol.CompileResponse result = new org.prlprg.server.protocol.CompileResponse(this);
      if (dataCase_ == 2) {
        result.data_ = data_;
      }
      if (dataCase_ == 3) {
        if (resultBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = resultBuilder_.build();
        }
      }
      result.dataCase_ = dataCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.prlprg.server.protocol.CompileResponse) {
        return mergeFrom((org.prlprg.server.protocol.CompileResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.prlprg.server.protocol.CompileResponse other) {
      if (other == org.prlprg.server.protocol.CompileResponse.getDefaultInstance()) return this;
      switch (other.getDataCase()) {
        case FAILURE: {
          dataCase_ = 2;
          data_ = other.data_;
          onChanged();
          break;
        }
        case RESULT: {
          mergeResult(other.getResult());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.prlprg.server.protocol.CompileResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.prlprg.server.protocol.CompileResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataCase_ = 0;
    private java.lang.Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }


    /**
     * <code>string failure = 2;</code>
     * @return The failure.
     */
    @java.lang.Override
    public java.lang.String getFailure() {
      java.lang.Object ref = "";
      if (dataCase_ == 2) {
        ref = data_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (dataCase_ == 2) {
          data_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string failure = 2;</code>
     * @return The bytes for failure.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFailureBytes() {
      java.lang.Object ref = "";
      if (dataCase_ == 2) {
        ref = data_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (dataCase_ == 2) {
          data_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string failure = 2;</code>
     * @param value The failure to set.
     * @return This builder for chaining.
     */
    public Builder setFailure(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  dataCase_ = 2;
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string failure = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFailure() {
      if (dataCase_ == 2) {
        dataCase_ = 0;
        data_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string failure = 2;</code>
     * @param value The bytes for failure to set.
     * @return This builder for chaining.
     */
    public Builder setFailureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      dataCase_ = 2;
      data_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.prlprg.server.protocol.CompiledFunction, org.prlprg.server.protocol.CompiledFunction.Builder, org.prlprg.server.protocol.CompiledFunctionOrBuilder> resultBuilder_;
    /**
     * <code>.rsh.server.protocol.CompiledFunction result = 3;</code>
     * @return Whether the result field is set.
     */
    @java.lang.Override
    public boolean hasResult() {
      return dataCase_ == 3;
    }
    /**
     * <code>.rsh.server.protocol.CompiledFunction result = 3;</code>
     * @return The result.
     */
    @java.lang.Override
    public org.prlprg.server.protocol.CompiledFunction getResult() {
      if (resultBuilder_ == null) {
        if (dataCase_ == 3) {
          return (org.prlprg.server.protocol.CompiledFunction) data_;
        }
        return org.prlprg.server.protocol.CompiledFunction.getDefaultInstance();
      } else {
        if (dataCase_ == 3) {
          return resultBuilder_.getMessage();
        }
        return org.prlprg.server.protocol.CompiledFunction.getDefaultInstance();
      }
    }
    /**
     * <code>.rsh.server.protocol.CompiledFunction result = 3;</code>
     */
    public Builder setResult(org.prlprg.server.protocol.CompiledFunction value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        resultBuilder_.setMessage(value);
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>.rsh.server.protocol.CompiledFunction result = 3;</code>
     */
    public Builder setResult(
        org.prlprg.server.protocol.CompiledFunction.Builder builderForValue) {
      if (resultBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        resultBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>.rsh.server.protocol.CompiledFunction result = 3;</code>
     */
    public Builder mergeResult(org.prlprg.server.protocol.CompiledFunction value) {
      if (resultBuilder_ == null) {
        if (dataCase_ == 3 &&
            data_ != org.prlprg.server.protocol.CompiledFunction.getDefaultInstance()) {
          data_ = org.prlprg.server.protocol.CompiledFunction.newBuilder((org.prlprg.server.protocol.CompiledFunction) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 3) {
          resultBuilder_.mergeFrom(value);
        }
        resultBuilder_.setMessage(value);
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>.rsh.server.protocol.CompiledFunction result = 3;</code>
     */
    public Builder clearResult() {
      if (resultBuilder_ == null) {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
        }
        resultBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.rsh.server.protocol.CompiledFunction result = 3;</code>
     */
    public org.prlprg.server.protocol.CompiledFunction.Builder getResultBuilder() {
      return getResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.rsh.server.protocol.CompiledFunction result = 3;</code>
     */
    @java.lang.Override
    public org.prlprg.server.protocol.CompiledFunctionOrBuilder getResultOrBuilder() {
      if ((dataCase_ == 3) && (resultBuilder_ != null)) {
        return resultBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 3) {
          return (org.prlprg.server.protocol.CompiledFunction) data_;
        }
        return org.prlprg.server.protocol.CompiledFunction.getDefaultInstance();
      }
    }
    /**
     * <code>.rsh.server.protocol.CompiledFunction result = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.prlprg.server.protocol.CompiledFunction, org.prlprg.server.protocol.CompiledFunction.Builder, org.prlprg.server.protocol.CompiledFunctionOrBuilder> 
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        if (!(dataCase_ == 3)) {
          data_ = org.prlprg.server.protocol.CompiledFunction.getDefaultInstance();
        }
        resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.prlprg.server.protocol.CompiledFunction, org.prlprg.server.protocol.CompiledFunction.Builder, org.prlprg.server.protocol.CompiledFunctionOrBuilder>(
                (org.prlprg.server.protocol.CompiledFunction) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 3;
      onChanged();;
      return resultBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rsh.server.protocol.CompileResponse)
  }

  // @@protoc_insertion_point(class_scope:rsh.server.protocol.CompileResponse)
  private static final org.prlprg.server.protocol.CompileResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.prlprg.server.protocol.CompileResponse();
  }

  public static org.prlprg.server.protocol.CompileResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompileResponse>
      PARSER = new com.google.protobuf.AbstractParser<CompileResponse>() {
    @java.lang.Override
    public CompileResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CompileResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CompileResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompileResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.prlprg.server.protocol.CompileResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

