// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package org.prlprg.server.protocol;

/** Protobuf type {@code rsh.server.protocol.Request} */
public final class Request extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:rsh.server.protocol.Request)
    RequestOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private Request() {}

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new Request();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              org.prlprg.server.protocol.HandshakeRequest.Builder subBuilder = null;
              if (payloadCase_ == 1) {
                subBuilder = ((org.prlprg.server.protocol.HandshakeRequest) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(
                      org.prlprg.server.protocol.HandshakeRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((org.prlprg.server.protocol.HandshakeRequest) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 1;
              break;
            }
          case 18:
            {
              org.prlprg.server.protocol.CompileRequest.Builder subBuilder = null;
              if (payloadCase_ == 2) {
                subBuilder = ((org.prlprg.server.protocol.CompileRequest) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(
                      org.prlprg.server.protocol.CompileRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((org.prlprg.server.protocol.CompileRequest) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 2;
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return org.prlprg.server.protocol.Protocol
        .internal_static_rsh_server_protocol_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.prlprg.server.protocol.Protocol
        .internal_static_rsh_server_protocol_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.prlprg.server.protocol.Request.class,
            org.prlprg.server.protocol.Request.Builder.class);
  }

  private int payloadCase_ = 0;
  private java.lang.Object payload_;

  public enum PayloadCase
      implements
          com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    HANDSHAKE(1),
    COMPILE(2),
    PAYLOAD_NOT_SET(0);
    private final int value;

    private PayloadCase(int value) {
      this.value = value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 1:
          return HANDSHAKE;
        case 2:
          return COMPILE;
        case 0:
          return PAYLOAD_NOT_SET;
        default:
          return null;
      }
    }

    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase getPayloadCase() {
    return PayloadCase.forNumber(payloadCase_);
  }

  public static final int HANDSHAKE_FIELD_NUMBER = 1;

  /**
   * <code>.rsh.server.protocol.HandshakeRequest handshake = 1;</code>
   *
   * @return Whether the handshake field is set.
   */
  @java.lang.Override
  public boolean hasHandshake() {
    return payloadCase_ == 1;
  }

  /**
   * <code>.rsh.server.protocol.HandshakeRequest handshake = 1;</code>
   *
   * @return The handshake.
   */
  @java.lang.Override
  public org.prlprg.server.protocol.HandshakeRequest getHandshake() {
    if (payloadCase_ == 1) {
      return (org.prlprg.server.protocol.HandshakeRequest) payload_;
    }
    return org.prlprg.server.protocol.HandshakeRequest.getDefaultInstance();
  }

  /** <code>.rsh.server.protocol.HandshakeRequest handshake = 1;</code> */
  @java.lang.Override
  public org.prlprg.server.protocol.HandshakeRequestOrBuilder getHandshakeOrBuilder() {
    if (payloadCase_ == 1) {
      return (org.prlprg.server.protocol.HandshakeRequest) payload_;
    }
    return org.prlprg.server.protocol.HandshakeRequest.getDefaultInstance();
  }

  public static final int COMPILE_FIELD_NUMBER = 2;

  /**
   * <code>.rsh.server.protocol.CompileRequest compile = 2;</code>
   *
   * @return Whether the compile field is set.
   */
  @java.lang.Override
  public boolean hasCompile() {
    return payloadCase_ == 2;
  }

  /**
   * <code>.rsh.server.protocol.CompileRequest compile = 2;</code>
   *
   * @return The compile.
   */
  @java.lang.Override
  public org.prlprg.server.protocol.CompileRequest getCompile() {
    if (payloadCase_ == 2) {
      return (org.prlprg.server.protocol.CompileRequest) payload_;
    }
    return org.prlprg.server.protocol.CompileRequest.getDefaultInstance();
  }

  /** <code>.rsh.server.protocol.CompileRequest compile = 2;</code> */
  @java.lang.Override
  public org.prlprg.server.protocol.CompileRequestOrBuilder getCompileOrBuilder() {
    if (payloadCase_ == 2) {
      return (org.prlprg.server.protocol.CompileRequest) payload_;
    }
    return org.prlprg.server.protocol.CompileRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (payloadCase_ == 1) {
      output.writeMessage(1, (org.prlprg.server.protocol.HandshakeRequest) payload_);
    }
    if (payloadCase_ == 2) {
      output.writeMessage(2, (org.prlprg.server.protocol.CompileRequest) payload_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (payloadCase_ == 1) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(
              1, (org.prlprg.server.protocol.HandshakeRequest) payload_);
    }
    if (payloadCase_ == 2) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(
              2, (org.prlprg.server.protocol.CompileRequest) payload_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof org.prlprg.server.protocol.Request)) {
      return super.equals(obj);
    }
    org.prlprg.server.protocol.Request other = (org.prlprg.server.protocol.Request) obj;

    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 1:
        if (!getHandshake().equals(other.getHandshake())) return false;
        break;
      case 2:
        if (!getCompile().equals(other.getCompile())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (payloadCase_) {
      case 1:
        hash = (37 * hash) + HANDSHAKE_FIELD_NUMBER;
        hash = (53 * hash) + getHandshake().hashCode();
        break;
      case 2:
        hash = (37 * hash) + COMPILE_FIELD_NUMBER;
        hash = (53 * hash) + getCompile().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.prlprg.server.protocol.Request parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static org.prlprg.server.protocol.Request parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static org.prlprg.server.protocol.Request parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static org.prlprg.server.protocol.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static org.prlprg.server.protocol.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static org.prlprg.server.protocol.Request parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static org.prlprg.server.protocol.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static org.prlprg.server.protocol.Request parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static org.prlprg.server.protocol.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static org.prlprg.server.protocol.Request parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static org.prlprg.server.protocol.Request parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static org.prlprg.server.protocol.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(org.prlprg.server.protocol.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /** Protobuf type {@code rsh.server.protocol.Request} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:rsh.server.protocol.Request)
      org.prlprg.server.protocol.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return org.prlprg.server.protocol.Protocol
          .internal_static_rsh_server_protocol_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.prlprg.server.protocol.Protocol
          .internal_static_rsh_server_protocol_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.prlprg.server.protocol.Request.class,
              org.prlprg.server.protocol.Request.Builder.class);
    }

    // Construct using org.prlprg.server.protocol.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return org.prlprg.server.protocol.Protocol
          .internal_static_rsh_server_protocol_Request_descriptor;
    }

    @java.lang.Override
    public org.prlprg.server.protocol.Request getDefaultInstanceForType() {
      return org.prlprg.server.protocol.Request.getDefaultInstance();
    }

    @java.lang.Override
    public org.prlprg.server.protocol.Request build() {
      org.prlprg.server.protocol.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.prlprg.server.protocol.Request buildPartial() {
      org.prlprg.server.protocol.Request result = new org.prlprg.server.protocol.Request(this);
      if (payloadCase_ == 1) {
        if (handshakeBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = handshakeBuilder_.build();
        }
      }
      if (payloadCase_ == 2) {
        if (compileBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = compileBuilder_.build();
        }
      }
      result.payloadCase_ = payloadCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.prlprg.server.protocol.Request) {
        return mergeFrom((org.prlprg.server.protocol.Request) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.prlprg.server.protocol.Request other) {
      if (other == org.prlprg.server.protocol.Request.getDefaultInstance()) return this;
      switch (other.getPayloadCase()) {
        case HANDSHAKE:
          {
            mergeHandshake(other.getHandshake());
            break;
          }
        case COMPILE:
          {
            mergeCompile(other.getCompile());
            break;
          }
        case PAYLOAD_NOT_SET:
          {
            break;
          }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.prlprg.server.protocol.Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.prlprg.server.protocol.Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int payloadCase_ = 0;
    private java.lang.Object payload_;

    public PayloadCase getPayloadCase() {
      return PayloadCase.forNumber(payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
            org.prlprg.server.protocol.HandshakeRequest,
            org.prlprg.server.protocol.HandshakeRequest.Builder,
            org.prlprg.server.protocol.HandshakeRequestOrBuilder>
        handshakeBuilder_;

    /**
     * <code>.rsh.server.protocol.HandshakeRequest handshake = 1;</code>
     *
     * @return Whether the handshake field is set.
     */
    @java.lang.Override
    public boolean hasHandshake() {
      return payloadCase_ == 1;
    }

    /**
     * <code>.rsh.server.protocol.HandshakeRequest handshake = 1;</code>
     *
     * @return The handshake.
     */
    @java.lang.Override
    public org.prlprg.server.protocol.HandshakeRequest getHandshake() {
      if (handshakeBuilder_ == null) {
        if (payloadCase_ == 1) {
          return (org.prlprg.server.protocol.HandshakeRequest) payload_;
        }
        return org.prlprg.server.protocol.HandshakeRequest.getDefaultInstance();
      } else {
        if (payloadCase_ == 1) {
          return handshakeBuilder_.getMessage();
        }
        return org.prlprg.server.protocol.HandshakeRequest.getDefaultInstance();
      }
    }

    /** <code>.rsh.server.protocol.HandshakeRequest handshake = 1;</code> */
    public Builder setHandshake(org.prlprg.server.protocol.HandshakeRequest value) {
      if (handshakeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        handshakeBuilder_.setMessage(value);
      }
      payloadCase_ = 1;
      return this;
    }

    /** <code>.rsh.server.protocol.HandshakeRequest handshake = 1;</code> */
    public Builder setHandshake(
        org.prlprg.server.protocol.HandshakeRequest.Builder builderForValue) {
      if (handshakeBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        handshakeBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 1;
      return this;
    }

    /** <code>.rsh.server.protocol.HandshakeRequest handshake = 1;</code> */
    public Builder mergeHandshake(org.prlprg.server.protocol.HandshakeRequest value) {
      if (handshakeBuilder_ == null) {
        if (payloadCase_ == 1
            && payload_ != org.prlprg.server.protocol.HandshakeRequest.getDefaultInstance()) {
          payload_ =
              org.prlprg.server.protocol.HandshakeRequest.newBuilder(
                      (org.prlprg.server.protocol.HandshakeRequest) payload_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 1) {
          handshakeBuilder_.mergeFrom(value);
        }
        handshakeBuilder_.setMessage(value);
      }
      payloadCase_ = 1;
      return this;
    }

    /** <code>.rsh.server.protocol.HandshakeRequest handshake = 1;</code> */
    public Builder clearHandshake() {
      if (handshakeBuilder_ == null) {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
        }
        handshakeBuilder_.clear();
      }
      return this;
    }

    /** <code>.rsh.server.protocol.HandshakeRequest handshake = 1;</code> */
    public org.prlprg.server.protocol.HandshakeRequest.Builder getHandshakeBuilder() {
      return getHandshakeFieldBuilder().getBuilder();
    }

    /** <code>.rsh.server.protocol.HandshakeRequest handshake = 1;</code> */
    @java.lang.Override
    public org.prlprg.server.protocol.HandshakeRequestOrBuilder getHandshakeOrBuilder() {
      if ((payloadCase_ == 1) && (handshakeBuilder_ != null)) {
        return handshakeBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 1) {
          return (org.prlprg.server.protocol.HandshakeRequest) payload_;
        }
        return org.prlprg.server.protocol.HandshakeRequest.getDefaultInstance();
      }
    }

    /** <code>.rsh.server.protocol.HandshakeRequest handshake = 1;</code> */
    private com.google.protobuf.SingleFieldBuilderV3<
            org.prlprg.server.protocol.HandshakeRequest,
            org.prlprg.server.protocol.HandshakeRequest.Builder,
            org.prlprg.server.protocol.HandshakeRequestOrBuilder>
        getHandshakeFieldBuilder() {
      if (handshakeBuilder_ == null) {
        if (!(payloadCase_ == 1)) {
          payload_ = org.prlprg.server.protocol.HandshakeRequest.getDefaultInstance();
        }
        handshakeBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                org.prlprg.server.protocol.HandshakeRequest,
                org.prlprg.server.protocol.HandshakeRequest.Builder,
                org.prlprg.server.protocol.HandshakeRequestOrBuilder>(
                (org.prlprg.server.protocol.HandshakeRequest) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 1;
      onChanged();
      ;
      return handshakeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
            org.prlprg.server.protocol.CompileRequest,
            org.prlprg.server.protocol.CompileRequest.Builder,
            org.prlprg.server.protocol.CompileRequestOrBuilder>
        compileBuilder_;

    /**
     * <code>.rsh.server.protocol.CompileRequest compile = 2;</code>
     *
     * @return Whether the compile field is set.
     */
    @java.lang.Override
    public boolean hasCompile() {
      return payloadCase_ == 2;
    }

    /**
     * <code>.rsh.server.protocol.CompileRequest compile = 2;</code>
     *
     * @return The compile.
     */
    @java.lang.Override
    public org.prlprg.server.protocol.CompileRequest getCompile() {
      if (compileBuilder_ == null) {
        if (payloadCase_ == 2) {
          return (org.prlprg.server.protocol.CompileRequest) payload_;
        }
        return org.prlprg.server.protocol.CompileRequest.getDefaultInstance();
      } else {
        if (payloadCase_ == 2) {
          return compileBuilder_.getMessage();
        }
        return org.prlprg.server.protocol.CompileRequest.getDefaultInstance();
      }
    }

    /** <code>.rsh.server.protocol.CompileRequest compile = 2;</code> */
    public Builder setCompile(org.prlprg.server.protocol.CompileRequest value) {
      if (compileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        compileBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }

    /** <code>.rsh.server.protocol.CompileRequest compile = 2;</code> */
    public Builder setCompile(org.prlprg.server.protocol.CompileRequest.Builder builderForValue) {
      if (compileBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        compileBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2;
      return this;
    }

    /** <code>.rsh.server.protocol.CompileRequest compile = 2;</code> */
    public Builder mergeCompile(org.prlprg.server.protocol.CompileRequest value) {
      if (compileBuilder_ == null) {
        if (payloadCase_ == 2
            && payload_ != org.prlprg.server.protocol.CompileRequest.getDefaultInstance()) {
          payload_ =
              org.prlprg.server.protocol.CompileRequest.newBuilder(
                      (org.prlprg.server.protocol.CompileRequest) payload_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2) {
          compileBuilder_.mergeFrom(value);
        }
        compileBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }

    /** <code>.rsh.server.protocol.CompileRequest compile = 2;</code> */
    public Builder clearCompile() {
      if (compileBuilder_ == null) {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
        }
        compileBuilder_.clear();
      }
      return this;
    }

    /** <code>.rsh.server.protocol.CompileRequest compile = 2;</code> */
    public org.prlprg.server.protocol.CompileRequest.Builder getCompileBuilder() {
      return getCompileFieldBuilder().getBuilder();
    }

    /** <code>.rsh.server.protocol.CompileRequest compile = 2;</code> */
    @java.lang.Override
    public org.prlprg.server.protocol.CompileRequestOrBuilder getCompileOrBuilder() {
      if ((payloadCase_ == 2) && (compileBuilder_ != null)) {
        return compileBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2) {
          return (org.prlprg.server.protocol.CompileRequest) payload_;
        }
        return org.prlprg.server.protocol.CompileRequest.getDefaultInstance();
      }
    }

    /** <code>.rsh.server.protocol.CompileRequest compile = 2;</code> */
    private com.google.protobuf.SingleFieldBuilderV3<
            org.prlprg.server.protocol.CompileRequest,
            org.prlprg.server.protocol.CompileRequest.Builder,
            org.prlprg.server.protocol.CompileRequestOrBuilder>
        getCompileFieldBuilder() {
      if (compileBuilder_ == null) {
        if (!(payloadCase_ == 2)) {
          payload_ = org.prlprg.server.protocol.CompileRequest.getDefaultInstance();
        }
        compileBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                org.prlprg.server.protocol.CompileRequest,
                org.prlprg.server.protocol.CompileRequest.Builder,
                org.prlprg.server.protocol.CompileRequestOrBuilder>(
                (org.prlprg.server.protocol.CompileRequest) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2;
      onChanged();
      ;
      return compileBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:rsh.server.protocol.Request)
  }

  // @@protoc_insertion_point(class_scope:rsh.server.protocol.Request)
  private static final org.prlprg.server.protocol.Request DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new org.prlprg.server.protocol.Request();
  }

  public static org.prlprg.server.protocol.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request> PARSER =
      new com.google.protobuf.AbstractParser<Request>() {
        @java.lang.Override
        public Request parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.prlprg.server.protocol.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
