//! Generated by Claude, modified for FIŘ constructs
#include "print_sexp.h"
#include "runtime.h"
#include <stdlib.h>

/* Forward declaration */
static void printSexpInternal(SEXP s, int indent);

/* Print indentation */
static void printIndent(int indent) {
  fprintf(stderr, "*   ");
  for (int i = 0; i < indent; i++) {
    fprintf(stderr, "  ");
  }
}

/* Print a symbol name safely */
static void printSymbol(SEXP s) {
  if (s == R_NilValue) {
    fprintf(stderr, "NULL");
  } else if (s == R_MissingArg) {
    fprintf(stderr, "<missing>");
  } else if (s == R_UnboundValue) {
    fprintf(stderr, "<unbound>");
  } else {
    fprintf(stderr, "%s", CHAR(PRINTNAME(s)));
  }
}

/* Print character string, escaping special characters */
static void printString(const char *str) {
  if (str == NULL) {
    fprintf(stderr, "NA");
    return;
  }
  fprintf(stderr, "\"");
  for (const char *p = str; *p; p++) {
    switch (*p) {
      case '\n': fprintf(stderr, "\\n"); break;
      case '\t': fprintf(stderr, "\\t"); break;
      case '\r': fprintf(stderr, "\\r"); break;
      case '\\': fprintf(stderr, "\\\\"); break;
      case '"':  fprintf(stderr, "\\\""); break;
      default:   fprintf(stderr, "%c", *p); break;
    }
  }
  fprintf(stderr, "\"");
}

/* Print vector elements */
static void printVector(SEXP s, int indent) {
  R_xlen_t n = XLENGTH(s);
  int sexptype = TYPEOF(s);

  /* Print type and length */
  switch (sexptype) {
    case LGLSXP:  fprintf(stderr, "logical(%lld)", (long long)n); break;
    case INTSXP:  fprintf(stderr, "integer(%lld)", (long long)n); break;
    case REALSXP: fprintf(stderr, "numeric(%lld)", (long long)n); break;
    case CPLXSXP: fprintf(stderr, "complex(%lld)", (long long)n); break;
    case STRSXP:  fprintf(stderr, "character(%lld)", (long long)n); break;
    case RAWSXP:  fprintf(stderr, "raw(%lld)", (long long)n); break;
    default:      fprintf(stderr, "vector(%lld)", (long long)n); break;
  }

  if (n == 0) {
    return;
  }

  /* Limit output for large vectors */
  R_xlen_t maxPrint = (n > 10) ? 10 : n;

  fprintf(stderr, " [");
  for (R_xlen_t i = 0; i < maxPrint; i++) {
    if (i > 0) fprintf(stderr, ", ");

    switch (sexptype) {
      case LGLSXP: {
        int val = LOGICAL(s)[i];
        if (val == NA_LOGICAL) fprintf(stderr, "NA");
        else fprintf(stderr, "%s", val ? "TRUE" : "FALSE");
        break;
      }
      case INTSXP: {
        int val = INTEGER(s)[i];
        if (val == NA_INTEGER) fprintf(stderr, "NA");
        else fprintf(stderr, "%d", val);
        break;
      }
      case REALSXP: {
        double val = REAL(s)[i];
        if (ISNA(val)) fprintf(stderr, "NA");
        else if (ISNAN(val)) fprintf(stderr, "NaN");
        else if (!R_FINITE(val)) fprintf(stderr, "%s", val > 0 ? "Inf" : "-Inf");
        else fprintf(stderr, "%.15g", val);
        break;
      }
      case CPLXSXP: {
        Rcomplex val = COMPLEX(s)[i];
        if (ISNA(val.r) || ISNA(val.i)) fprintf(stderr, "NA");
        else fprintf(stderr, "%.15g%+.15gi", val.r, val.i);
        break;
      }
      case STRSXP: {
        SEXP elem = STRING_ELT(s, i);
        if (elem == NA_STRING) fprintf(stderr, "NA");
        else printString(CHAR(elem));
        break;
      }
      case RAWSXP: {
        fprintf(stderr, "%02x", RAW(s)[i]);
        break;
      }
    }
  }

  if (n > maxPrint) {
    fprintf(stderr, ", ... (%lld more)", (long long)(n - maxPrint));
  }
  fprintf(stderr, "]");
}

/* Print a pairlist (used for arguments, etc.) */
static void printPairlist(SEXP s, int indent) {
  int first = 1;
  for (SEXP p = s; p != R_NilValue; p = CDR(p)) {
    if (!first) {
      fprintf(stderr, ",\n");
      printIndent(indent);
    }
    first = 0;

    SEXP tag = TAG(p);
    if (tag != R_NilValue) {
      printSymbol(tag);
      fprintf(stderr, " = ");
    }
    printSexpInternal(CAR(p), indent);
  }
}

/* Print attributes */
static void printAttributes(SEXP s, int indent) {
  SEXP attrs = ATTRIB(s);
  if (attrs == R_NilValue) return;

  for (SEXP a = attrs; a != R_NilValue; a = CDR(a)) {
    fprintf(stderr, "\n");
    printIndent(indent + 1);

    SEXP tag = TAG(a);
    if (tag != R_NilValue) {
      fprintf(stderr, "@ ");
      printSymbol(tag);
      fprintf(stderr, " = ");
    }
    printSexpInternal(CAR(a), indent + 1);
  }
}

/* Main internal printing function */
static void printSexpInternal(SEXP s, int indent) {
  if (s == R_NilValue) {
    fprintf(stderr, "NULL");
    return;
  }
  if (s == R_MissingArg) {
    fprintf(stderr, "<missing arg>");
    return;
  }
  if (s == R_UnboundValue) {
    fprintf(stderr, "<unbound value>");
    return;
  }

  int type = TYPEOF(s);

  switch (type) {
    case NILSXP:
      fprintf(stderr, "NULL");
      break;

    case SYMSXP:
      fprintf(stderr, "symbol: ");
      printSymbol(s);
      break;

    case LISTSXP:
      fprintf(stderr, "pairlist(\n");
      printIndent(indent + 1);
      printPairlist(s, indent + 1);
      fprintf(stderr, ")");
      printAttributes(s, indent);
      break;

    case CLOSXP: {
      // Print differently if FIŘ
      Fir_FunctionData *data;
      bool is_fir = Fir_is_compiled_closure(s, &data);
      if (is_fir) {
        fprintf(stderr, "clos(%s)", data->name);
      } else {
        fprintf(stderr, "closure");
      }

      fprintf(stderr, " {\n");
      if (!is_fir) {
              printIndent(indent + 1);
              fprintf(stderr, "formals: ");
              printSexpInternal(FORMALS(s), indent + 1);
              fprintf(stderr, "\n");
              printIndent(indent + 1);
              fprintf(stderr, "body: ");
              printSexpInternal(BODY(s), indent + 1);
              fprintf(stderr, "\n");
      }
      printIndent(indent + 1);
      fprintf(stderr, "env: ");
      printSexpInternal(CLOENV(s), indent + 1);
      fprintf(stderr, "\n");
      printIndent(indent);
      fprintf(stderr, "}");
      printAttributes(s, indent);
      break;
    }
    case ENVSXP:
      if (s == R_GlobalEnv) {
        fprintf(stderr, "<environment: R_GlobalEnv>");
      } else if (s == R_BaseEnv) {
        fprintf(stderr, "<environment: base>");
      } else if (s == R_EmptyEnv) {
        fprintf(stderr, "<environment: R_EmptyEnv>");
      } else if (R_IsNamespaceEnv(s)) {
        SEXP name = R_NamespaceEnvSpec(s);
        if (name != R_NilValue && TYPEOF(name) == STRSXP && LENGTH(name) > 0) {
          fprintf(stderr, "<namespace: %s>", CHAR(STRING_ELT(name, 0)));
        } else {
          fprintf(stderr, "<namespace: ?>");
        }
      } else if (R_IsPackageEnv(s)) {
        SEXP name = R_PackageEnvName(s);
        if (name != R_NilValue && TYPEOF(name) == STRSXP) {
          fprintf(stderr, "<package: %s>", CHAR(STRING_ELT(name, 0)));
        } else {
          fprintf(stderr, "<package: ?>");
        }
      } else {
        fprintf(stderr, "<environment: %p>", (void *)s);
      }
      break;
    case PROMSXP: {
      // Print differently and with type if FIŘ
      Fir_PromiseGlobalData *global_data;
      Fir_PromiseLocalData *local_data;
      bool is_fir = Fir_is_compiled_promise(s, &global_data, &local_data);
      if (is_fir) {
        fprintf(stderr, "p(");
        Fir_print_type(global_data->value_type);
        fprintf(stderr, " ");
        Fir_print_effects(global_data->reflect);
        fprintf(stderr, ")");
      } else {
        fprintf(stderr, "promise");
      }

      // Don't force the promise - just show its structure
      fprintf(stderr, " {\n");
      if (!is_fir) {
        printIndent(indent + 1);
        fprintf(stderr, "expr: ");
        printSexpInternal(PREXPR(s), indent + 1);
        fprintf(stderr, "\n");
      }
      printIndent(indent + 1);
      fprintf(stderr, "env: ");
      if (PRENV(s) == R_NilValue) {
        fprintf(stderr, "<forced or NULL>");
      } else {
        printSexpInternal(PRENV(s), indent + 1);
      }
      fprintf(stderr, "\n");
      // Only show value if already forced
      if (PROMISE_IS_EVALUATED(s)) {
        printIndent(indent + 1);
        fprintf(stderr, "value: ");
        printSexpInternal(PRVALUE(s), indent + 1);
        fprintf(stderr, "\n");
      }
      printIndent(indent);
      fprintf(stderr, "}");
      break;
    }
    case LANGSXP:
      fprintf(stderr, "call: ");
      /* Print as function call */
      printSexpInternal(CAR(s), indent);
      fprintf(stderr, "(");
      if (CDR(s) != R_NilValue) {
        fprintf(stderr, "\n");
        printIndent(indent + 1);
        printPairlist(CDR(s), indent + 1);
      }
      fprintf(stderr, ")");
      printAttributes(s, indent);
      break;

    case SPECIALSXP:
      fprintf(stderr, "<special: .Primitive(\"%s\")>", PRIMNAME(s));
      break;

    case BUILTINSXP:
      fprintf(stderr, "<builtin: .Primitive(\"%s\")>", PRIMNAME(s));
      break;

    case CHARSXP:
      fprintf(stderr, "CHARSXP: ");
      printString(CHAR(s));
      break;

    case LGLSXP:
    case INTSXP:
    case REALSXP:
    case CPLXSXP:
    case STRSXP:
    case RAWSXP:
      printVector(s, indent);
      printAttributes(s, indent);
      break;

    case VECSXP: {
      R_xlen_t n = XLENGTH(s);
      fprintf(stderr, "list(%lld)", (long long)n);
      if (n > 0) {
        R_xlen_t maxPrint = (n > 10) ? 10 : n;
        fprintf(stderr, " {\n");

        /* Get names if available */
        SEXP names = getAttrib(s, R_NamesSymbol);

        for (R_xlen_t i = 0; i < maxPrint; i++) {
          printIndent(indent + 1);
          fprintf(stderr, "[[");
          if (names != R_NilValue && TYPEOF(names) == STRSXP && i < XLENGTH(names)) {
            SEXP nm = STRING_ELT(names, i);
            if (nm != NA_STRING && CHAR(nm)[0] != '\0') {
              fprintf(stderr, "%s", CHAR(nm));
            } else {
              fprintf(stderr, "%lld", (long long)(i + 1));
            }
          } else {
            fprintf(stderr, "%lld", (long long)(i + 1));
          }
          fprintf(stderr, "]] = ");
          printSexpInternal(VECTOR_ELT(s, i), indent + 1);
          fprintf(stderr, "\n");
        }
        if (n > maxPrint) {
          printIndent(indent + 1);
          fprintf(stderr, "... (%lld more elements)\n", (long long)(n - maxPrint));
        }
        printIndent(indent);
        fprintf(stderr, "}");
      }
      /* Print attributes except names (already handled) */
      SEXP attrs = ATTRIB(s);
      if (attrs != R_NilValue) {
        int hasNonNameAttr = 0;
        for (SEXP a = attrs; a != R_NilValue; a = CDR(a)) {
          if (TAG(a) != R_NamesSymbol) {
            hasNonNameAttr = 1;
            break;
          }
        }
        if (hasNonNameAttr) {
          for (SEXP a = attrs; a != R_NilValue; a = CDR(a)) {
            if (TAG(a) != R_NamesSymbol) {
              fprintf(stderr, "\n");
              printIndent(indent + 1);

              fprintf(stderr, "@ ");
              printSymbol(TAG(a));
              fprintf(stderr, " = ");
              printSexpInternal(CAR(a), indent + 1);
            }
          }
        }
      }
      break;
    }

    case EXPRSXP: {
      R_xlen_t n = XLENGTH(s);
      fprintf(stderr, "expression(%lld)", (long long)n);
      if (n > 0) {
        R_xlen_t maxPrint = (n > 10) ? 10 : n;
        fprintf(stderr, " {\n");
        for (R_xlen_t i = 0; i < maxPrint; i++) {
          printIndent(indent + 1);
          fprintf(stderr, "[%lld] ", (long long)(i + 1));
          printSexpInternal(VECTOR_ELT(s, i), indent + 1);
          fprintf(stderr, "\n");
        }
        if (n > maxPrint) {
          printIndent(indent + 1);
          fprintf(stderr, "... (%lld more)\n", (long long)(n - maxPrint));
        }
        printIndent(indent);
        fprintf(stderr, "}");
      }
      printAttributes(s, indent);
      break;
    }

    case BCODESXP:
      fprintf(stderr, "<bytecode: %p>", (void *)s);
      break;

    case EXTPTRSXP:
      fprintf(stderr, "<external pointer: %p>", R_ExternalPtrAddr(s));
      printAttributes(s, indent);
      break;

    case WEAKREFSXP:
      fprintf(stderr, "<weak reference>");
      break;

    case S4SXP:
      fprintf(stderr, "S4 object");
      printAttributes(s, indent);
      break;

    case DOTSXP:
      fprintf(stderr, "... {\n");
      printIndent(indent + 1);
      printPairlist(s, indent + 1);
      fprintf(stderr, "\n");
      printIndent(indent);
      fprintf(stderr, "}");
      break;

    case ANYSXP:
      fprintf(stderr, "<any>");
      break;

    default:
      fprintf(stderr, "<unknown type %d>", type);
      break;
  }
}

void Fir_print_sexp(SEXP s) {
  printSexpInternal(s, 0);
}