// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: routes.proto

#include "routes.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_routes_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_routes_2eproto = nullptr;
const uint32_t TableStruct_routes_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_routes_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014routes.proto\032\016messages.proto2g\n\016Compil"
  "eService\022.\n\007Compile\022\017.CompileRequest\032\020.C"
  "ompileResponse\"\000\022%\n\004Init\022\014.InitRequest\032\r"
  ".InitResponse\"\0002\303\001\n\013FactService\022)\n\nGetCo"
  "ntext\022\017.ContextRequest\032\010.Context\"\000\0224\n\017Ge"
  "tTypeFeedback\022\020.FeedbackRequest\032\r.TypeFe"
  "edback\"\000\022%\n\tGetValues\022\r.ValueRequest\032\007.V"
  "alues\"\000\022,\n\013GetFunction\022\020.FunctionRequest"
  "\032\t.Function\"\000B\023\n\021org.prlprg.serverb\006prot"
  "o3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_routes_2eproto_deps[1] = {
  &::descriptor_table_messages_2eproto,
};
static ::_pbi::once_flag descriptor_table_routes_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_routes_2eproto = {
    false, false, 362, descriptor_table_protodef_routes_2eproto,
    "routes.proto",
    &descriptor_table_routes_2eproto_once, descriptor_table_routes_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_routes_2eproto::offsets,
    nullptr, file_level_enum_descriptors_routes_2eproto,
    file_level_service_descriptors_routes_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_routes_2eproto_getter() {
  return &descriptor_table_routes_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_routes_2eproto(&descriptor_table_routes_2eproto);

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
